name: CI

on:
  push:
    branches:
    - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ionic build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POOLPAL_1A57B }}'
          projectId: poolpal-1a57b
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
